version: "3.0"
services:
 order-services:
  
  build: 
   context: .
   dockerfile: ./docker/Dockerfile
  container_name: order
  ports:
    - 8082:8082
  environment:
    - spring.cloud.stream.kafka.binder.defaultBrokerPort=29092
    - spring.cloud.stream.kafka.binder.brokers=kafka

 